[package]
name = "flashloader"
version = "0.1.0"
edition = "2021"

[dependencies]
cortex-m = { version = "0.7", features = ["critical-section-single-core"]}
cortex-m-rt = "0.7"
embedded-io = "0.7"
defmt = "1"
defmt-rtt = { version = "1" }
panic-probe = { version = "1", features = ["print-defmt"] }
num_enum = { version = "0.7", default-features = false }
cobs = { version = "0.5", default-features = false, features = ["defmt"] }
fugit = "0.5"
arbitrary-int = "2"
embassy-sync = "0.8"
embedded-io-async = "0.7"
embassy-time = { version = "0.5", features = ["defmt-timestamp-uptime-ms"] }
static_cell = "2"
postcard = { version = "1", features = ["use-defmt"] }
spacepackets = { version = "0.18", default-features = false, features = ["defmt"] }
serde = { version = "1", default-features = false }
# Even though we do not use this directly, we need to activate this feature explicitely
# so that RTIC compiles because thumv6 does not have CAS operations natively.
portable-atomic = {version = "1", features = ["unsafe-assume-single-core"]}
flashloader-types = { path = "../../host/flashloader-types", features = ["defmt"] }

rtic = { version = "2", features = ["thumbv6-backend"] }

[dependencies.va108xx-hal]
version = "0.14"
path = "../va108xx-hal"
features = ["defmt", "embassy-oc30-oc31"]

[dependencies.vorago-reb1]
version = "0.10"
path = "../vorago-reb1"

[package.metadata.cargo-machete]
ignored = ["portable-atomic", "cortex-m-rt"]
