[package]
name = "slot-blinky"
version = "0.1.0"
edition = "2024"

[workspace]

[features]
slot-a = []
slot-b = []

[dependencies]
cortex-m-rt = "0.7"
embedded-hal = "1"
defmt = "1"
defmt-rtt = "1"
panic-probe = { version = "1", features = ["defmt"] }
va108xx-hal = { path = "../../va108xx-hal", features = ["defmt"] }

[build-dependencies]
flashloader-types = { path = "../../../host/flashloader-types" }

[profile.dev]
codegen-units = 1
debug = 2
debug-assertions = true # <-
incremental = false
# This is problematic for stepping..
# opt-level = 'z'         # <-
overflow-checks = true  # <-

# cargo build/run --release
[profile.release]
codegen-units = 1
debug = 2
debug-assertions = false # <-
incremental = false
lto = 'fat'
opt-level = 3            # <-
overflow-checks = false  # <-
