[package]
name = "flashloader"
version = "0.1.0"
edition = "2021"

[dependencies]
cortex-m = "0.7"
# Not used directly. The feature makes the image set VTOR itself, no matter who started it.
cortex-m-rt = { version = "0.7", features = ["set-vtor"] }
embedded-io = "0.7"
defmt-rtt = "1"
defmt = "1"
panic-probe = { version = "1", features = ["defmt"] }
static_cell = "2"
fugit = "0.5"
ringbuf = { version = "0.5", default-features = false }
once_cell = { version = "1", default-features = false, features = ["critical-section"] }
postcard = { version = "1", features = ["use-defmt"] }
spacepackets = { version = "0.18", default-features = false, features = ["defmt"] }
cobs = { version = "0.5", default-features = false }
flashloader-types = { path = "../../host/flashloader-types", features = ["defmt"] }

va416xx-hal = { version = "0.7", features = ["va41630", "defmt", "time-driver-tim14-tim15"], path = "../va416xx-hal" }

rtic = { version = "2", features = ["thumbv7-backend"] }
embassy-time = { version = "0.5", features = ["tick-hz-1_000", "generic-queue-8"] }
