name: va108xx-ci
on: [push, pull_request]
defaults:
  run:
    working-directory: ./va108xx

jobs:
  check:
    name: Check build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          targets: "thumbv6m-none-eabi"
      - uses: Swatinem/rust-cache@v2
        with:
          workspaces: va108xx
      - run: cargo check --target thumbv6m-none-eabi
      - run: cargo check --target thumbv6m-none-eabi --examples
      - run: cargo check -p va108xx --target thumbv6m-none-eabi --all-features
      - run: cargo check -p va108xx-hal --target thumbv6m-none-eabi --features "defmt"

  build:
    name: Check build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          targets: "thumbv6m-none-eabi"
      - uses: Swatinem/rust-cache@v2
        with:
          workspaces: va108xx
      - uses: taiki-e/install-action@v2
        with:
          tool: flip-link
      # The flashloader does not fit into flash in a debug build.
      - run: cargo build --target thumbv6m-none-eabi --release

  fmt:
    name: Check formatting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt
      - run: cargo fmt --all -- --check

  docs:
    name: Check Documentation Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@nightly
        with:
          targets: "thumbv6m-none-eabi"
      - uses: Swatinem/rust-cache@v2
        with:
          workspaces: va108xx
      - run: RUSTDOCFLAGS="--cfg docsrs --generate-link-to-definition -Z unstable-options" cargo +nightly doc -p va108xx --all-features
      - run: RUSTDOCFLAGS="--cfg docsrs --generate-link-to-definition -Z unstable-options" cargo +nightly doc -p va108xx-hal --features "defmt, embassy-oc30-oc31" --no-deps
      - run: RUSTDOCFLAGS="--cfg docsrs --generate-link-to-definition -Z unstable-options" cargo +nightly doc -p vorago-reb1 --no-deps

  clippy:
    name: Clippy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          targets: "thumbv6m-none-eabi"
      - uses: Swatinem/rust-cache@v2
        with:
          workspaces: va108xx
      - run: cargo clippy --target thumbv6m-none-eabi -- -D warnings
