name: va416xx-ci
on: [push, pull_request]
defaults:
  run:
    working-directory: ./va416xx

jobs:
  check:
    name: Check build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          targets: "thumbv7em-none-eabihf"
      - uses: Swatinem/rust-cache@v2
        with:
          workspaces: va416xx
      - run: cargo check --target thumbv7em-none-eabihf
      - run: cargo check --target thumbv7em-none-eabihf --examples
      - run: cargo check -p va416xx --target thumbv7em-none-eabihf --all-features
      - run: cargo check -p va416xx-hal --target thumbv7em-none-eabihf --features "defmt va41630"

  build:
    name: Check build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          targets: "thumbv7em-none-eabihf"
      - uses: Swatinem/rust-cache@v2
        with:
          workspaces: va416xx
      - uses: taiki-e/install-action@v2
        with:
          tool: flip-link
      - run: cargo build --target thumbv7em-none-eabihf

  fmt:
    name: Check formatting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - run: cargo fmt --all -- --check

  docs:
    name: Check Documentation Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@nightly
        with:
          targets: "thumbv7em-none-eabihf"
      - uses: Swatinem/rust-cache@v2
        with:
          workspaces: va416xx
      - run: RUSTDOCFLAGS="--cfg docsrs --generate-link-to-definition -Z unstable-options" cargo +nightly doc -p va416xx
      - run: RUSTDOCFLAGS="--cfg docsrs --generate-link-to-definition -Z unstable-options" cargo +nightly doc -p va416xx-hal --features va41630 --no-deps
      - run: RUSTDOCFLAGS="--cfg docsrs --generate-link-to-definition -Z unstable-options" cargo +nightly doc -p vorago-peb1 --no-deps

  clippy:
    name: Clippy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          targets: "thumbv7em-none-eabihf"
      - uses: Swatinem/rust-cache@v2
        with:
          workspaces: va416xx
      - run: cargo clippy --target thumbv7em-none-eabihf -- -D warnings
